baseURL: 'https://marijus001.github.io/'
languageCode: 'en-us'
title: 'Lysiu'
theme: 'PaperMod'

params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10